### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by ericgaspar**
- Remove old version https://github.com/YunoHost-Apps/pihole_ynh/pull/74
- Upgrade tp 5.9

### CODE REVIEW

**Comment by ericgaspar** [comment]
!testme

**Comment by ericgaspar** [comment]
Shall we merge this?

**Review by yalh76 — APPROVED** [review]

**Comment by ericgaspar** [comment]
!testme

**Comment by ericgaspar** [comment]
!testme

**Pull request merged**
